env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
    'no-unused-vars': 'off'
    '@typescript-eslint/no-unused-vars': 'error'
    '@typescript-eslint/no-explicit-any': 'off' # remove to set to warn
    'brace-style': 'off'
    '@typescript-eslint/brace-style': ['error']
    '@typescript-eslint/class-name-casing': ['error']
    'func-call-spacing': 'off'
    '@typescript-eslint/func-call-spacing': ['error', 'never']
    'indent': 'off'
    '@typescript-eslint/indent': ['error', 4]
    'no-extra-parens': 'off'
    '@typescript-eslint/no-extra-parens': ['error']
    '@typescript-eslint/no-floating-promises': 'off' # change to 'warn'
    '@typescript-eslint/no-for-in-array': 'error'
    '@typescript-eslint/no-inferrable-types': 'error'

