allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  inferno: true
  lmdb: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - devextreme-angular@26.1.5
  - devextreme-themebuilder@26.1.5
  - devextreme@26.1.5
