name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Authenticate to GitHub Package
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

    - name: Get DevExtreme Version
      run: export DEVEXTREME_INTERNAL_VERSION=$(npm pkg get dependencies.devextreme | tr -d '"')

    - name: Install devextreme-internal
      run: npm i devextreme@npm:@devexpress/devextreme-internal@$DEVEXTREME_INTERNAL_VERSION --registry https://npm.pkg.github.com --no-save

    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRET }}
        BRANCH: gh-pages
        FOLDER: dist/devextreme-themebuilder-app
        CLEAN: true

