name: Deploy

on:
  push:
    branches:
      - ci

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRET }}
        BRANCH: gh-pages
        FOLDER: dist/devextreme-themebuilder-app
        CLEAN: true

